import Head from "next/head";
import React from "react";
import Footer from "../components/footer/Footer";
import Header from "../components/header/Header";

function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Restho - Resturent React Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/images/icon/logo-icon.svg" />
      </Head>
      <Header />
      {children}
      <Footer />
    </>
  );
}

export default Layout;
